{
 "title": "Simple APM",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Endpoint Latencies in ms  (Last minute)",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by (http_method,http_target)(increase(traces_spanmetrics_latency_sum{http_method=~\".+\", http_target=~\".+\"}[1m]) / increase(traces_spanmetrics_latency_count{http_method=~\".+\", http_target=~\".+\"}[1m])))"
    }
   ]
  },
  {
   "title": "All Endpoint Latencies in ms (Last 10 mins)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum by (http_method,http_target)(increase(traces_spanmetrics_latency_sum{http_method=~\".+\", http_target=~\".+\"}[10m]) / increase(traces_spanmetrics_latency_count{http_method=~\".+\", http_target=~\".+\"}[10m]))"
    }
   ]
  },
  {
   "title": "95th Percentile Response Latencies (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mythical_request_times_bucket[15s])) by (le, beast))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Autologged Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{job=\"agent\"} | logfmt | status=\"STATUS_CODE_ERROR\""
    }
   ]
  }
 ]
}