version: "2.1"
volumes:
  grafana:
services:
  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
  promexample:
    build: ./promexample
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
  node-server:
    build: ./node-server
    ports:
      - "4000:4000"
  grafana:
    image: grafana/grafana
    volumes:
      - "grafana:/var/lib/grafana"
    ports:
      - "3000:3000"
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
