extensions:
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

exporters:
  logging:
  otlp:
    endpoint: tempo:55680
    insecure: true
    headers:
      x-scope-orgid: example

processors:
  batch:

service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [jaeger]
      processors: [batch]
      exporters: [otlp, logging]

