server: 
  log_level: debug

logs:
    configs:
    - name: loki
      clients:
        - url: http://loki:3100/loki/api/v1/push
          external_labels:
            job: agent
    positions_directory: /tmp/positions

traces:
  configs:
  - name: latencyEndpoint
    receivers:
      jaeger:
        protocols:
          thrift_binary:
            endpoint: "0.0.0.0:6832"
    remote_write:
      - endpoint: tempo:55680
        insecure: true
    tail_sampling:
      policies:
        - latency:
            threshold_ms: 100
    automatic_logging:
        backend: logs_instance
        logs_instance_name: loki
        roots: true
        processes: false
        spans: false
        span_attributes:
          - "service.name"
          - "http.target"
        overrides:
          trace_id_key: "traceId"

  - name: statusEndpoint
    receivers:
      jaeger:
        protocols:
          thrift_binary:
            endpoint: "0.0.0.0:6833"
    remote_write:
      - endpoint: tempo:55680
        insecure: true
    tail_sampling:
      policies:
        - status_code:
            status_codes:
              - ERROR
    automatic_logging:
        backend: logs_instance
        logs_instance_name: loki
        roots: true
        processes: false
        spans: false
        span_attributes:
          - "service.name"
          - "otel.status_code"
        overrides:
          trace_id_key: "traceId"
          loki_tag: tempo